In [1]:
import numpy as np

# 1. Create

In [2]:
# 3-dimensional array
# z, x, y
zeroes = np.zeros((2,2,2))
zeroes

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [4]:
full = np.full((2,2,2), 7)
full

array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]])

In [3]:
data = np.random.rand(2,3,4)
data

array([[[0.39221009, 0.13652389, 0.25511852, 0.8155153 ],
        [0.90972557, 0.1114414 , 0.49529569, 0.75019009],
        [0.27073254, 0.28202062, 0.29784552, 0.81588164]],

       [[0.31834838, 0.59296659, 0.80404859, 0.3710219 ],
        [0.6745543 , 0.85528926, 0.54666819, 0.7588404 ],
        [0.09977387, 0.06861438, 0.82088945, 0.52399028]]])

In [5]:
ones = np.ones((2,2,2))
ones

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [6]:
# create an array of lists of numbers
arr = np.array([[1,2,3,4],[1,2,3,4]])
arr

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [7]:
type(arr)

numpy.ndarray

# 2. Read

In [9]:
# Attributes of arrays
shape = data.shape
size = data.size
types = data.dtype

print("Shape:", shape)
print("Size:", size)
print("types:", types)

Shape: (2, 3, 4)
Size: 24
types: float64


In [11]:
# Slicing
arr = data[0]
slicer = data[0][0:2]

print("data[0] =", arr)
print("\ndata[0][0:2] =", slicer)

data[0] = [[0.39221009 0.13652389 0.25511852 0.8155153 ]
 [0.90972557 0.1114414  0.49529569 0.75019009]
 [0.27073254 0.28202062 0.29784552 0.81588164]]

data[0][0:2] = [[0.39221009 0.13652389 0.25511852 0.8155153 ]
 [0.90972557 0.1114414  0.49529569 0.75019009]]


In [13]:
reverse = data[-1] # last index
singleval = data[0][0][0]

print("data[-1] =", reverse)
print("\ndata[0][0][0] =", singleval)

data[-1] = [[0.31834838 0.59296659 0.80404859 0.3710219 ]
 [0.6745543  0.85528926 0.54666819 0.7588404 ]
 [0.09977387 0.06861438 0.82088945 0.52399028]]

data[0][0][0] = 0.39221008895587417


In [14]:
data

array([[[0.39221009, 0.13652389, 0.25511852, 0.8155153 ],
        [0.90972557, 0.1114414 , 0.49529569, 0.75019009],
        [0.27073254, 0.28202062, 0.29784552, 0.81588164]],

       [[0.31834838, 0.59296659, 0.80404859, 0.3710219 ],
        [0.6745543 , 0.85528926, 0.54666819, 0.7588404 ],
        [0.09977387, 0.06861438, 0.82088945, 0.52399028]]])

# 3. Update

In [24]:
# create 2 variables to play with them
list1 = np.random.randint(1, high=10, size=10) 
list2 = np.random.randint(1, high=10, size=10) 

print("list1 =", list1, "\n")
print("list2 =", list2)

list1 = [2 4 3 5 5 3 3 9 4 7] 

list2 = [2 3 6 9 3 3 9 5 8 7]


In [25]:
# Basic Math
add = np.add(list1, list2)
sub = np.subtract(list1, list2)
div = np.divide(list1, list2)
mult = np.multiply(list1, list2)
dot = np.dot(list1, list2)

In [27]:
print("add:", add, "\n")
print("subtract:", sub, "\n")
print("divide:", div, "\n")
print("multiply:", mult, "\n")
print("dot:", dot)

add: [ 4  7  9 14  8  6 12 14 12 14] 

subtract: [ 0  1 -3 -4  2  0 -6  4 -4  0] 

divide: [1.         1.33333333 0.5        0.55555556 1.66666667 1.
 0.33333333 1.8        0.5        1.        ] 

multiply: [ 4 12 18 45 15  9 27 45 32 49] 

dot: 256


In [28]:
# Statistical Functions
sqrt = np.sqrt(25)
ab = np.abs(-2)
power = np.power(2,7)
log = np.log(25)
exp = np.exp([2,3])
mins = np.min(list1)
maxs = np.max(list1)

In [29]:
print("sqrt:", sqrt, "\n")
print("abs:", ab, "\n")
print("power:", power, "\n")
print("log:", log, "\n")
print("exp:", exp, "\n")
print("max:", maxs, "\n")
print("min:", mins)

sqrt: 5.0 

abs: 2 

power: 128 

log: 3.2188758248682006 

exp: [ 7.3890561  20.08553692] 

max: 9 

min: 2


In [38]:
print("before:",data,"\n")
data[0][0][0] = 700
print("after:",data)

before: [[[0.39221009 0.13652389 0.25511852 0.8155153 ]
  [0.90972557 0.1114414  0.49529569 0.75019009]
  [0.27073254 0.28202062 0.29784552 0.81588164]]

 [[0.31834838 0.59296659 0.80404859 0.3710219 ]
  [0.6745543  0.85528926 0.54666819 0.7588404 ]
  [0.09977387 0.06861438 0.82088945 0.52399028]]] 

after: [[[7.00000000e+02 1.36523886e-01 2.55118516e-01 8.15515302e-01]
  [9.09725571e-01 1.11441402e-01 4.95295692e-01 7.50190089e-01]
  [2.70732541e-01 2.82020618e-01 2.97845516e-01 8.15881639e-01]]

 [[3.18348382e-01 5.92966590e-01 8.04048595e-01 3.71021896e-01]
  [6.74554302e-01 8.55289256e-01 5.46668186e-01 7.58840402e-01]
  [9.97738679e-02 6.86143788e-02 8.20889454e-01 5.23990276e-01]]]


In [39]:
# sorting
data.sort()
data

array([[[1.36523886e-01, 2.55118516e-01, 8.15515302e-01, 7.00000000e+02],
        [1.11441402e-01, 4.95295692e-01, 7.50190089e-01, 9.09725571e-01],
        [2.70732541e-01, 2.82020618e-01, 2.97845516e-01, 8.15881639e-01]],

       [[3.18348382e-01, 3.71021896e-01, 5.92966590e-01, 8.04048595e-01],
        [5.46668186e-01, 6.74554302e-01, 7.58840402e-01, 8.55289256e-01],
        [6.86143788e-02, 9.97738679e-02, 5.23990276e-01, 8.20889454e-01]]])

In [41]:
print("Before:",data.shape,"\n")
# make it 2,2 and not care about last value
# it will be automatically calculated
data = data.reshape((2,2,-1)) 
print("After:",data.shape)

Before: (2, 3, 4) 

After: (2, 2, 6)


In [42]:
# Append Array
zerosarr = np.zeros((8))
print(zerosarr)
zerosarr = np.append(zerosarr, [3,4])
print(zerosarr)

[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 3. 4.]


In [43]:
# insert at specified index (2), and value (1)
zerosarr = np.insert(zerosarr, 2, 1)
print(zerosarr)

[0. 0. 1. 0. 0. 0. 0. 0. 0. 3. 4.]


# 4. Delete

In [47]:
print("initially:\n",data,"\n")
# delete the first array in the 2 sub arrays
## level=0, axis=1(row)
np.delete(data, 0, axis=1) 
# it returns the new array, won't update the original one

initially:
 [[[1.36523886e-01 2.55118516e-01 8.15515302e-01 7.00000000e+02
   1.11441402e-01 4.95295692e-01]
  [7.50190089e-01 9.09725571e-01 2.70732541e-01 2.82020618e-01
   2.97845516e-01 8.15881639e-01]]

 [[3.18348382e-01 3.71021896e-01 5.92966590e-01 8.04048595e-01
   5.46668186e-01 6.74554302e-01]
  [7.58840402e-01 8.55289256e-01 6.86143788e-02 9.97738679e-02
   5.23990276e-01 8.20889454e-01]]] 



array([[[0.75019009, 0.90972557, 0.27073254, 0.28202062, 0.29784552,
         0.81588164]],

       [[0.7588404 , 0.85528926, 0.06861438, 0.09977387, 0.52399028,
         0.82088945]]])

In [45]:
# save the array
np.save("numpy_array", data)

In [46]:
# reload the array
test = np.load("numpy_array.npy")
print(test)

[[[1.36523886e-01 2.55118516e-01 8.15515302e-01 7.00000000e+02
   1.11441402e-01 4.95295692e-01]
  [7.50190089e-01 9.09725571e-01 2.70732541e-01 2.82020618e-01
   2.97845516e-01 8.15881639e-01]]

 [[3.18348382e-01 3.71021896e-01 5.92966590e-01 8.04048595e-01
   5.46668186e-01 6.74554302e-01]
  [7.58840402e-01 8.55289256e-01 6.86143788e-02 9.97738679e-02
   5.23990276e-01 8.20889454e-01]]]
